### ISSUE TITLE
RuntimeError running debluring code

### ISSUE THREAD

**Issue by Woody-Wan** [yuanzhi-zhu/DiffPIR#44]
Hello, I really appreciate this work and it is a great method to solve the linear inverse problem. But I noticed that when I tried to reproduce your code in debluring task using the demo test, there is a mismatch on the dimension. Not sure whether you have any idea whay might be the problem. Thank you in advnace!

```
24-11-26 22:24:02.158 : eta:0, zeta:0.30000000000000004, lambda:7, guidance_scale:1.0
torch.eye(3):  torch.Size([3, 3])
k_4d:  torch.Size([16, 61, 61])
Traceback (most recent call last):
  File "./DiffPIR/main_ddpir.py", line 602, in <module>
    main()
  File "./DiffPIR/main_ddpir.py", line 573, in main
    test_results_ave = test_rho(config)
                       ^^^^^^^^^^^^^^^^
  File "./DiffPIR/main_ddpir.py", line 305, in test_rho
    k_4d = torch.einsum('ab,cd->abcd',torch.eye(3).to(device),k_4d)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./py311/lib/python3.12/site-packages/torch/functional.py", line 386, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: einsum(): the number of subscripts in the equation (2) does not match the number of dimensions (3) for operand 1 and no ellipsis was given

```

**Comment by yuanzhi-zhu** [comment]
Thanks for pointing out
please replace
`k_4d = torch.einsum('ab,cd->abcd',torch.eye(3).to(device),k_4d)`
with
`k_4d = k_4d.unsqueeze(1)`

I have push the changes to this repo

**Comment by Woody-Wan** [comment]
Very cool, it works! Thank you!
